export enum cor {
    Azul = "Azul",
    Preto = "Preto",
    Amarelo = "Amarelo",
    Verde = "Verde",
    Vermelho = "Vermelho",
    Prata = "Prata",
    Branco = "Branco",
    Cinza = "Cinza",
    Marrom = "Marrom",
    Laranja = "Laranja",
    Roxo = "Roxo",
    Rosa = "Rosa",
    Bege = "Bege",
    Ouro = "Ouro",
    Bronze = "Bronze",
    Champagne = "Champagne",
    Cobre = "Cobre",
    Turquesa = "Turquesa",
    Violeta = "Violeta",
    Bordô = "Bordô",
  }